### ISSUE TITLE
Onderhoudsgeschiedenis Inzien (Monteur)

### ISSUE THREAD

**Issue by KSlingerland** [hanaim-devops/devops-bp-pitstop-uitbreiding-team-monaco#1]
# User Story
Als monteur wil ik de volledige onderhoudshistorie van een voertuig kunnen inzien zodat ik een overzicht heb van alle eerder uitgevoerde reparaties en onderhoudswerkzaamheden.

# Acceptatiecriteria

- [ ] Voertuig dossier is te bereiken via vehicle management
- [ ] Monteurs kunnen alle eerder uitgevoerde werkzaamheden (in chronologische volgorde) zien voor een bepaald voertuig.
- [ ] Het overzicht bevat datum, beschrijving van de werkzaamheden en een type reparatie (Enum: Onderhoud, Scadeherstel.. ect...)
- [ ] Monteurs kunnen door de geschiedenis bladeren en zoeken op datum of type reparatie.

**Comment by mwoaksx** [comment]
Nog wat feedbackpuntjes van Bart erin verwerken:
<feedback hier> (kan de notulen niet vinden😅 dit er neerzetten wanneer het kan)
